version: '3'

networks:
  web:
    driver: bridge

services:
  embedding-service:
    image: "ghcr.io/data-house/embedding-service:main"
    networks:
      - web
    environment:
      - MODEL_NAME=T-Systems-onsite/cross-en-de-roberta-sentence-transformer
    volumes:
      - ./models:/root/.cache/torch/sentence_transformers
    ports:
      - "5000:5000"